# Generated by Django 4.1.3 on 2022-12-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField()),
                ('cantidadPersonas', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('observasion', models.CharField(max_length=100)),
            ],
        ),
    ]
